#pragma once  // aqui solo hay librerias de clase, es la agrupación
#include "LasersMenu.h"
#include "Ayudantes.h"
#include "Spot.h"
#include "Mejoras.h"
#include "Entidades.h"
#include "Tambores.h"
#include "Habilidades.h"
#include "Carros.h"
#include "Gwen.h"
#include "Enemigos.h"