#pragma once  // aqui solo hay librerias de clase, es la agrupación
#include "LasersMenu.h"
#include "Ayudantes.h"
#include "Enemigos.h"
#include "Mejoras.h"
#include "Obstaculos.h"
#include "Protagonistas.h"
#include "Tambores.h"
#include "Habilidades.h"
#include "Proyectiles.h"